name: publish-pr

on: [pull_request]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build . --tag ghcr.io/mhkarimi1383/simple-store:${{ github.event.pull_request.number }}
          docker push ghcr.io/mhkarimi1383/simple-store:${{ github.event.pull_request.number }}
