name: publish-dev

on:
  push:
    tags:
      - "*"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build . --tag ghcr.io/mhkarimi1383/simple-store:stable --tag ghcr.io/mhkarimi1383/simple-store:${{ github.ref_name }}
          docker push ghcr.io/mhkarimi1383/simple-store:stable
          docker push ghcr.io/mhkarimi1383/simple-store:${{ github.ref_name }}
