name: publish-letest

on:
  push:
    branches:
      - "master"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mhkarimi1383
          password: ${{ secrets.GHCR_PUSH_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build . --tag ghcr.io/mhkarimi1383/simple-store:latest --tag ghcr.io/mhkarimi1383/simple-store:${GITHUB_SHA:0:8}
          docker push ghcr.io/mhkarimi1383/simple-store:latest
          docker push ghcr.io/mhkarimi1383/simple-store:${GITHUB_SHA:0:8}
